spring:
  datasource: #DB 접속정보
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main
    password: root
    username: root


  mvc: #JSP 설정
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  thymeleaf: #Thymeleaf 설정
    #JSP와 같이 사용시 뷰 구분을 위해 컨트롤러가 뷰 이름을 반환시 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정
    view-names: thymeleaf/*
    prefix: classpath:templates/
    suffix: .html
    #파일 수정시 반영하려면 하면 재시작을 해줘야 한다. 브라우저 새로고침시 수정사항 반영을 취해 cache=false 설정(운영시 true)
    cache: false
    check-template-location: true

#mybatis: #Mybatis 설정
  #type-aliases-package: com.god.bo.*.vo
  #mapper-locations: mybatis/**/*.xml


logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: error
